### ISSUE TITLE
The variant of visformer

### ISSUE THREAD

**Issue by RongKaiWeskerMA** [DongSky/few-shot-vit#1]
Hi Bowen

Thanks for opensource the inference code. I am just curious which variant of the visformer achieves the best results in Table 5 on mini-ImageNet? Is it visformer_80_small?

**Comment by DongSky** [comment]
Hi Rongkai
visformer_small_80 (namely visformer_micro_80 in the config file) achieves the best result in Table 5. The architecture detail of visformer_small_80 is shown as Table A in the Appendix (12.5M parameters in total, fair comparisons with ResNet-12 based methods). 
https://github.com/DongSky/few-shot-vit/blob/main/test_phase/models/visformer.py#L483
