### ISSUE TITLE
timm version

### ISSUE THREAD

**Issue by JIAOJIAYUASD** [DongSky/few-shot-vit#3]
hello, I met a question when run your code as follow?
`Traceback (most recent call last):
  File "train_classifier.py", line 296, in <module>
    main(config)
  File "train_classifier.py", line 133, in main
    lr_scheduler = CosineLRScheduler(optimizer, warmup_lr_init=float(config['optimizer_args']['warmup_lr']), t_initial=config['max_epoch'], cycle_decay=0.1, warmup_t=int(config['optimizer_args']['warmup']))
TypeError: __init__() got an unexpected keyword argument 'cycle_decay'
`
I think it's the version of timm package is not right, and the requirement in your code just say that is the latest version. can your provide the version of timm package??

**Comment by DongSky** [comment]
Hi [JIAOJIAYUASD](https://github.com/JIAOJIAYUASD)
The timm I used is version 0.5.4.
For earlier version, e.g., 0.3.2, you can replace cycle_decay by decay_rate.

**Comment by JIAOJIAYUASD** [comment]
Thanks for your reply, and I solve the problem.
